package com.sample
 
import com.sample.DroolsTest.Message;
import pl.poznan.put.fc.Question;
 
rule "Hello World"
    when
        m : Message( status == Message.HELLO, myMessage : message )
    then
    	Object[] answ = {"Tak", "Nie"};
    	(new Question("Moje piekne pytanie?", answ)).ask();
        System.out.println( myMessage );
        m.setMessage( "Goodbye cruel world kurwo" );
        m.setStatus( Message.GOODBYE );
        update( m );
end

rule "GoodBye"
    when
        Message( status == Message.GOODBYE, myMessage : message )
    then
        System.out.println( myMessage );
end
